### PR TITLE
Smart CI

### PR DESCRIPTION
**Pull request by ranweiler**

### CODE REVIEW

**Comment by nealmcb** [comment]
Offhand, looks good.
I suggest adding some documentation to note that if someone adds a global config file or some other way that client or server tests depend on outside files, this optimization might miss something.
What tests have you run?

**Comment by ranweiler** [comment]
@nealmcb previously, this branch had commits that changed the READMEs in the relevant subdirectories. I then killed them and force-pushed, one-by-one, to make sure clean directories wouldn't have their checks spuriously run.

**Comment by ranweiler** [comment]
I'll add a comment about that edge case. @kiniry, would you like to see that "gotcha" flagged anywhere special?

**Comment by nealmcb** [comment]
Re the gotcha about how building is optimized, I'd suggest noting it in docs/25_developer.md

**Comment by ranweiler** [comment]
@nealmcb good call! I'll add something there, as well as a comment in the CI file itself.

**Comment by nealmcb** [comment]
Those are great warnings, ranweiler. I'm good with this now, but I guess I can only recommend merging.

**Comment by dmzimmerman** [comment]
Also, given that we actually have documentation and specifications that build, we should probably add such builds (typechecking of the PVS, generation of the PDF from the PVS, generation of the PDF from the Markdown) to continuous integration at some point. A topic for another PR, when we have more time.

**Pull request merged**
