### PR TITLE
Updates to support CVR import progress

### PR DESCRIPTION
**Pull request by dmzimmerman**
This is an attempt to add progress indication to long-running CVR imports, from the server side.

### CODE REVIEW

**Comment by ranweiler** [comment]
The response to my (only) request to the `import-cvr-export` endpoint has body:
```
{
  "result": "county 1 is already importing CVRs, try later"
}
```

**Comment by ranweiler** [comment]
Also: the `approximate_record_count` is not appearing the `UploadedFile` JSON serialization because it has a custom JSON adapter which needs to be updated, too.

**Comment by dmzimmerman** [comment]
Well, I should have known it wouldn't quite work on the first, rushed try. :) 

`approximate_record_count` in JSON addressed in 020c85ff

**Comment by dmzimmerman** [comment]
Interestingly, the re-upload failure is almost certainly something that would have happened _before_, as well, in the event of contests with ties...

**Comment by dmzimmerman** [comment]
Yup. It's definitely something that would have happened before; we just hadn't tested it. I was removing the contest records before removing the tied contest "contest to audit" records in the DoS dashboard. Addressed in 170cebec.

IMPORTANT NOTE: if the ballot manifest is re-uploaded while CVRs are still being imported, the CVR import _will fail_ (properly, because the ballot manifest has changed from underneath it). Thus, it is probably a good idea to disable the ballot manifest upload button while CVRs are being imported.

**Pull request merged**
