### PR TITLE
Initial thoughts on deployment considerations

### PR DESCRIPTION
**Pull request by dmzimmerman**
If anybody has any comments on any of this, feel free.

### CODE REVIEW

**Comment by nealmcb** [comment]
Reads well and makes sense to me, though I haven't reviewed the Postgres options.

**Comment by nealmcb** [comment]
Sorry - clicked the wrong button. I think it can be merged, but better to have a more db-savvy reviewer.

**Comment by dmzimmerman** [comment]
I'm done with this for now (have to focus on other tasks), but this information should be solid enough to be merged into master.

**Comment by ranweiler** [comment]
@dmzimmerman, approved, just rebase and you'll be good to merge.

**Pull request merged**
