### PR TITLE
File upload UX

### PR DESCRIPTION
**Pull request by ranweiler**
Towards #364. We need to add more info, but this is a start.

### CODE REVIEW

**Comment by ranweiler** [comment]
@kiniry yes, that's correct. Actually, I think I can improve that with a small change, hold please.

**Comment by ranweiler** [comment]
@kiniry okay, I was incorrect: differentiating with a nice display of the reasons for failure is enough work that I'd rather get this in, and improve it in another PR tomorrow.

**Comment by kiniry** [comment]
I'm ok with that, so long as an issue is/was filed.

**Comment by ranweiler** [comment]
@kiniry yeah, I'm just leaving #364 open.

**Pull request merged**
