### PR TITLE
SoS sprint

### PR DESCRIPTION
**Pull request by ranweiler**
Dashboard
- [x] Layout
- [x] County progress summary
- [x] Contest summary

Contest overview:
- [x] Breadcrumb
- [x] Table
- [x] Link to each detail page in table

Contest detail:
- [x] Breadcrumb
- [x] Render contest info
- [x] Render data based on path

County overview:
- [x] Breadcrumb
- [x] Table
- [x] Link to each detail page in table

County detail:
- [x] Breadcrumb
- [x] Render county info
- [x] Render data based on path

Admin:
- [x] Nav bar
- [x] Breadcrumb
- [x] Forms

Seed:
- [x] Nav bar
- [x] Breadcrumb
- [x] Seed form
- [x] Nav buttons

Ballot list
- [x] Nav bar
- [x] Breadcrumb
- [x] Upload form
- [x] Back button
- [x] Launch audit button

General
- [x] Div styling
- [x] State passing
- [x] Login state
- [x] Audit admin paths

### CODE REVIEW

**Comment by dmzimmerman** [comment]
Some general comments on the SoS dashboard:

- the login page says "county login"
- the inconsistency between "County Updates" and "Contest updates." as titles is odd.
- "Target and Current Risk Limits by Contest" doesn't match the "Target Risk Limit" and "Risk Level" columns
- What does "# ballots submitted" mean on the counties page? Number of ballots they uploaded (that presumably had their hash verified)? Number of ballots they have submitted info for during the audit?
- The creation date widget looks super strange in my Chrome: 
screen shot 2017-07-31 at 18 31 35

**Comment by ranweiler** [comment]
1. Login title fixed
1. Title discrepancy fixed.
1. The mismatched risk limit section was leftover placeholder text, removed.
1. Ballots to be audited, but we could show either/both. Really, we will need to rework this for phase 2, as exactly what we want to show here has not been discussed enough.
1. Looking into the date input.

**Comment by ranweiler** [comment]
Added a temporary page to log in as a specific user type for testing.

**Comment by ranweiler** [comment]
Date input fixed both when using `npm start` and the result of `script/dist`.

**Pull request merged**
